title: Dinner
description: Deciding is Delicious
url: https://austinmunichsocial.github.io

remote_eheme: piayyai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
